name: Push video-thumb-gen

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Build Image And Push to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: goodboyymh/video-thumb-gen
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"